apiVersion: v1
kind: Pod
metadata:
  name: k8s-for-beginners
spec:
  containers:
  - name: main
    image: packtworkshops/the-kubernetes-workshop:k8s-for-beginners
  - name: mugur
    image: 20041986/custom-netshoot-ubuntu
    command: ["sh", "-c", "sleep 3600"]
    # This container will run indefinitely with sleep

